# Generated by kpex 0.2.5
crashbackups stop
drc off
gds read /foss/designs/thesis/thesis_hp/Designs/final_tapeout_submissions/ledamp/2_layout/final_layout_before_fillering/FMD_QNC_ota_final_decoup.gds
load FMD_QNC_ota_final_decoup
select top cell
flatten FMD_QNC_ota_final_decoup_flat
load FMD_QNC_ota_final_decoup_flat
cellname delete FMD_QNC_ota_final_decoup -noprompt
cellname rename FMD_QNC_ota_final_decoup_flat FMD_QNC_ota_final_decoup
select top cell
extract path /foss/designs/thesis/thesis_hp/Designs/final_tapeout_submissions/ledamp/3_pex/output/FMD_QNC_ota_final_decoup__FMD_QNC_ota_final_decoup/magic_CC
extract all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/thesis/thesis_hp/Designs/final_tapeout_submissions/ledamp/3_pex/output/FMD_QNC_ota_final_decoup__FMD_QNC_ota_final_decoup/magic_CC -o /foss/designs/thesis/thesis_hp/Designs/final_tapeout_submissions/ledamp/3_pex/output/FMD_QNC_ota_final_decoup__FMD_QNC_ota_final_decoup/magic_CC/FMD_QNC_ota_final_decoup.pex.spice
quit -noprompt