# Generated by kpex 0.2.5
crashbackups stop
drc off
gds read /foss/designs/IHP-AnalogAcademy/modules/module_1_bandgap_reference/part_3_layout/BGR_layout/final_bandgapreference/full_bandgap_layout_pads.gds
load full_bandgap
select top cell
flatten full_bandgap_flat
load full_bandgap_flat
cellname delete full_bandgap -noprompt
cellname rename full_bandgap_flat full_bandgap
select top cell
extract path /foss/designs/thesis/thesis_hp/Designs/otas/3_kpex/full_bandgap_layout_pads__full_bandgap/magic_CC
extract all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/thesis/thesis_hp/Designs/otas/3_kpex/full_bandgap_layout_pads__full_bandgap/magic_CC -o /foss/designs/thesis/thesis_hp/Designs/otas/3_kpex/full_bandgap_layout_pads__full_bandgap/magic_CC/full_bandgap.pex.spice
quit -noprompt