project:
  type: book
  output-dir: _book

book:
  title: "Assessing the feasibility of developing and taping-out an analog block for LED driver control using IHP-Open-PDK and IIC-OSIC-TOOLS"
  author:
    - name: "Priyanka Toyni"
      email: "ptoyni@hs-bremen.de"
      orcid: ""
      corresponding: true
      roles: "Lead author"
      affiliation:
        - id: hsb
        - name: "Hochschule Bremen - City University of Applied Sciences"
          city: "Bremen"
          state: "Germany"
          url: "https://www.hs-bremen.de"
          department: "School of Electrical Engineering and Computer Sciences"
    - name: "Hrishikesh Pangavhane"
      email: "hpangavhane@hs-bremen.de"
      orcid: ""
      corresponding: true
      roles: "Lead author"
      affiliation:
        - ref: hsb

  date: "28 November 2026"
  date-format: "MMMM YYYY"
  # license: "Apache-2.0 license"

  reader-mode: true

  page-footer:
    left: |
      Assessing the feasibility of developing and taping-out an analog block for LED driver control using IHP-Open-PDK and IIC-OSIC-TOOLS.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  # cover-image: images/hsb-logo.png
  # favicon: images/hsb-logo.png
  site-url: https://ptoyni.github.io/thesis_hp/
  repo-url: https://github.com/ptoyni/thesis_hp
  repo-branch: main
  repo-actions: [edit,issue]
  downloads: [pdf,epub]

  chapters:
    - frontmatter/01-dedication.qmd
    - frontmatter/02-declaration.qmd
    - frontmatter/03-abstract.qmd
    - frontmatter/04-acknowledgements.qmd
    - index.qmd
    - content/_sec_introduction.qmd
    - content/_sec_Requirements_AES.qmd
    - part: Circuit Design
      chapters:
        - content/_sec_OTA_design.qmd   
        - content/_sec_cornersimulations.qmd   
    - part: Physical Design 
      chapters:
        - content/_sec_into_layout.qmd
        - content/_sec_OTA_layout.qmd
        - content/_sec_DRC.qmd
        - content/_sec_LVS.qmd
        - content/_sec_parasitics_prevention.qmd
        - content/_sec_layout_finalsteps.qmd
    - part: Post-Layout Simulation
      chapters:
        - content/_sec_postlayout_simulation.qmd
        - content/_sec_OTA_pex.qmd
    - content/_sec_conclusion.qmd
    - references.qmd
    
  appendices:
    - content/_appendix_A.qmd
    - content/_appendix_B.qmd
    - content/_appendix_C.qmd

  output-file: "thesis_hp"


# Bibliography
bibliography: _bibliography/references.bib
csl: _bibliography/ieee.csl

format:
  html:
    theme: simplex
    fontsize: 1.2em
    linestretch: 1.7
    mainfont: Helvetica Neue, Helvetica, Arial, sans
    monofont: Cascadia Mono, Menlo, Consolas, Courier New, Courier
    backgroundcolor: "white"
    fontcolor: "black"
    highlight-style: github

  epub:
    theme: flatly
    fontsize: 1.2em
    linestretch: 1.7
    mainfont: Helvetica Neue, Helvetica, Arial, sans
    monofont: Cascadia Mono, Menlo, Consolas, Courier New, Courier
    backgroundcolor: "white"
    fontcolor: "black"
    highlight-style: github

  pdf:
    documentclass: scrbook
    classoption: [twoside]
    papersize: a4
    keep-tex: true

    # Table of contents
    toc: true
    toc-depth: 3
    toc-title: "Table of contents"
    lof: true
    lot: true

    number-sections: true
    number-depth: 2
        
    # Setup page layout
    papersize: a4

    geometry:
      - inner=3cm
      - outer=4cm
      - top=3cm
      - bottom=4cm
      - headsep=22pt
      - headheight=11pt
      - footskip=33pt
      - ignorehead
      - ignorefoot
      - heightrounded

    fontsize: 11pt
    pdfengine: xelatex
    
    mainfont: "Times New Roman"
    sansfont: "Arial"
    monofont: "Courier New"
    mathfont: "TeX Gyre Termes Math"
    
    # geometry: 
    #   - top=30mm
    #   - left=20mm
    #   - heightrounded
    # hyperrefoptions:
    #   - linktoc=all
    # colorlinks: true
    # linkcolor: "blue" 

    # # Fonts
    # mainfont: "Calibri"

    
    # Thesis customization 
    include-in-header:
      - frontmatter/header.tex
    template-partials:
     - frontmatter/before-body.tex
     - frontmatter/toc.tex

