# Generated by kpex 0.2.5
crashbackups stop
drc off
gds read /foss/designs/thesis/thesis_hp/Designs/otas/2_layout/foldedcascode_nmos_withdummies.gds
load foldedcascode_nmos_withdummies
select top cell
flatten foldedcascode_nmos_withdummies_flat
load foldedcascode_nmos_withdummies_flat
cellname delete foldedcascode_nmos_withdummies -noprompt
cellname rename foldedcascode_nmos_withdummies_flat foldedcascode_nmos_withdummies
select top cell
extract path /foss/designs/thesis/thesis_hp/Designs/otas/3_kpex/foldedcascode_nmos_withdummies__foldedcascode_nmos_withdummies/magic_CC
extract all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/thesis/thesis_hp/Designs/otas/3_kpex/foldedcascode_nmos_withdummies__foldedcascode_nmos_withdummies/magic_CC -o /foss/designs/thesis/thesis_hp/Designs/otas/3_kpex/foldedcascode_nmos_withdummies__foldedcascode_nmos_withdummies/magic_CC/foldedcascode_nmos_withdummies.pex.spice
quit -noprompt