# Declaration of Authorship {.unnumbered .unlisted}

We hereby declare that we have written the present work independently
and have not used any sources or aids other than those indicated.

The passages of this work that were taken from other works, either
verbatim or in terms of meaning, are marked with indications of their
origin.

This declaration also applies to the graphics, sketches, and visual
representations contained in the work. We have not submitted this work,
either in the same or similar form, nor in excerpts, as part of an
examination or academic requirement.

We certify that the electronic version of the submitted work is
identical to the printed version, and we agree to an electronic review
of the work using plagiarism detection software.

We certify that we have not used any AI-based tools whose use has not
been agreed upon in writing with the examiner. I am aware that the use
of texts or other content and products generated by AI-based tools does
not guarantee their quality. We assume responsibility for the work
submitted and for its content. We further certify that our own creative
input predominates in the present work. All verbatim or paraphrased
contributions and quotations, as well as all sections created, written,
and/or edited with the aid of AI-based tools, are marked and documented
by us. The form of disclosure will be agreed upon between the examiner
and the examinee.

We are aware that a violation of the points mentioned may have
examination-related consequences and, in particular, may lead to the
examination performance being graded as \"insufficient\" or the academic
performance as \"failed\". In cases of repeated or serious misconduct,
expulsion may occur.


First name and surname:

Student ID Number:

Bremen,

Signature
