# Generated by kpex 0.2.5
crashbackups stop
drc off
gds read /foss/designs/IHP-AnalogAcademy/modules/module_1_bandgap_reference/part_3_layout/BGR_layout/final_bandgapreference/full_bandgap_layout.gds
load complete_schematic_pads
select top cell
flatten complete_schematic_pads_flat
load complete_schematic_pads_flat
cellname delete complete_schematic_pads -noprompt
cellname rename complete_schematic_pads_flat complete_schematic_pads
select top cell
extract path /foss/designs/thesis/thesis_hp/Designs/otas/3_kpex/full_bandgap_layout__complete_schematic_pads/magic_CC
extract all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/thesis/thesis_hp/Designs/otas/3_kpex/full_bandgap_layout__complete_schematic_pads/magic_CC -o /foss/designs/thesis/thesis_hp/Designs/otas/3_kpex/full_bandgap_layout__complete_schematic_pads/magic_CC/complete_schematic_pads.pex.spice
quit -noprompt