# Generated by kpex 0.2.5
crashbackups stop
drc off
gds read /foss/designs/thesis/thesis_hp/Designs/otas/2_layout/ota_final.gds
load ota_final
select top cell
flatten ota_final_flat
load ota_final_flat
cellname delete ota_final -noprompt
cellname rename ota_final_flat ota_final
select top cell
extract path /foss/designs/thesis/thesis_hp/Designs/otas/3_kpex/ota_final__ota_final/magic_CC
extract all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/thesis/thesis_hp/Designs/otas/3_kpex/ota_final__ota_final/magic_CC -o /foss/designs/thesis/thesis_hp/Designs/otas/3_kpex/ota_final__ota_final/magic_CC/ota_final.pex.spice
quit -noprompt